apiVersion: v1
kind: Service
metadata:
  labels:
    app: mail
  name: mail
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8025
    appProtocol: http
  - name: smtp
    port: 25
    protocol: TCP
    targetPort: 1025
    appProtocol: smtp
  type: ClusterIP
  selector:
    app: mail
